language: python
install:
  - pip install -r requirements.txt
before_install:
    - ./ecr_credentials.sh
    - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
    - unzip awscli-bundle.zip
    - ./awscli-bundle/install -b ~/bin/aws
    - export PATH=~/bin:$PATH
    - pip install boto3

script:
    - python ./aws_ipset.py
  # after_success:

deploy:
  provider: wafv2
  region: us-east-1
  access_key_id: AKIAQBHSRDAZUQWGM7WA
  secret_access_key: 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
  app: Test
  on:
    all_branches: true
